### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by pcwalton** [pcwalton/font-kit#1]
Can't be done until cocoa, core-foundation, core-graphics, and core-text are published to crates.io. Also dwrote-rs needs the additions to be merged.

**Comment by jrmuizel** [comment]
I think this is done now.

**Comment by jrmuizel** [comment]
Or rather all of the dependencies should be available on crates.io

**Comment by pcwalton** [comment]
Great, on it now.

**Comment by pcwalton** [comment]
Blocked on https://github.com/servo/rust-freetype/issues/54

**Comment by pcwalton** [comment]
Done! https://crates.io/crates/font-kit
