### ISSUE TITLE
Calls to raster_bounds after rasterize_glyph don't work properly

### ISSUE THREAD

**Issue by wezm** [pcwalton/font-kit#14]
All calls to `raster_bounds` after the first `rasterize_glyph` return very small bounds like 1x1. See this gist for reproduction (it's just the `render-glyph` example with the `raster_bounds` and `rasterize_glyph` parts repeated.

https://gist.github.com/wezm/cecc28f3446d73dc2ee3a1822fd15f89

Reproduced with multiple fonts on the following platforms with font-kit 159c016:
* FreeBSD 11.2 with Freetype 2.9.1
* Arch Linux with Freetype 2.9.1

**Comment by zacps** [comment]
I can also reproduce on Arch Linux with Freetype 2.9.2, font-kit 159c01697789c1c36c9c1ae93102a7f0ef1ab4b4.

**Comment by ashkitten** [comment]
confirmed, also running into this issue
