### ISSUE TITLE
Support for Arabic or RTL languages

### ISSUE THREAD

**Issue by fasihrana** [pcwalton/font-kit#22]
Will this library support RTL languages?

The substitutions happen one character at a time in this library, so I'm not sure how this could be achieved. Yet getting the correct glyphs is important for languages that have joining characters.

**Comment by RazrFalcon** [comment]
@pcwalton Is this out of scope? I think that this is [skribo](https://github.com/linebender/skribo) job.

**Comment by pcwalton** [comment]
The character-to-glyph mapping is documented as being best effort only and not suitable for high quality typography, including international text. You should pair font-kit with HarfBuzz or a library that wraps HarfBuzz, such as skribo, for production use.
