### ISSUE TITLE
Origin has no effect in freetype rasterize_glyph

### ISSUE THREAD

**Issue by raphlinus** [pcwalton/font-kit#33]
The `origin` argument translates the glyph in the CoreText loader but not the freetype one. In addition, the default seems to be the top-left alignment in freetype, but bottom-left in CoreText.

**Comment by jneem** [comment]
I'd be interested in taking a stab at this, if someone could clarify the desired behavior. (Judging by #43, I'm guessing it should be top-left.)

On a related note, I'd be grateful if someone could explain what `Loader::origin` is supposed to do. I couldn't understand the docstring...

**Comment by jrmuizel** [comment]
https://github.com/pcwalton/font-kit/pull/75 fixes this.
