### ISSUE TITLE
Font size is scalar

### ISSUE THREAD

**Issue by raphlinus** [pcwalton/font-kit#34]
The `point_size` argument to `rasterize_glyph` (and `raster_bounds`) is a scalar, but in general we might need an affine transform (to apply fake-italic). If we used a full 3x2 affine, this would also subsume the `origin` argument.

**Comment by jrmuizel** [comment]
WebRender has a FontTransform that it uses for this kind of thing:

https://searchfox.org/mozilla-central/rev/f0ef51bfafc8ad0c3a2f523bf076edc57dc4891a/gfx/wr/webrender/src/glyph_rasterizer/mod.rs#34
