### ISSUE TITLE
Additional collaborators? 

### ISSUE THREAD

**Issue by RazrFalcon** [pcwalton/font-kit#57]
It would be nice, if you could add me as a collaborator to this project. At least temporarily.
Currently, I'm trying to maintain my own fork, but it's troublesome, since there are a lot of changes/fixes and most of them are depending on each other. And the patches review process is pretty slow at the moment.

**Comment by pcwalton** [comment]
Do you need more patches upstream?

**Comment by RazrFalcon** [comment]
- #55
- #56
- better testing (a big one)
- sub/super positions
- baselines?
- `select_best_match` returns an invalid result when it has unknown fonts (no bugreport yet)
- loaders/freetype.rs rewrite, just like with fontconfig
- reduce/localize unsafe
- rustfmt

**Comment by pcwalton** [comment]
OK, I just added you.

**Comment by RazrFalcon** [comment]
Thanks! I will not do any radical changes without your permission.
