### ISSUE TITLE
Type mismatch on Raspberry Pi 3B+

### ISSUE THREAD

**Issue by Eiyeron** [pcwalton/font-kit#8]
Hello.

WHile trying to build amethyst for a few tests, I ended up having compilation errors on font-kit. Looks like many types are mismatching on this device. I'll be attaching a log as a file  as it takes quite a bit of vertical space.
Here's my current rust compiler toolchains
```
installed toolchains
--------------------
stable-armv7-unknown-linux-gnueabihf
nightly-armv7-unknown-linux-gnueabihf
active toolchain
----------------
stable-armv7-unknown-linux-gnueabihf (default)
rustc 1.29.2 (17a9dc751 2018-10-05)
```

Thank you and have a nice day.

[build log here](https://github.com/pcwalton/font-kit/files/2476865/build.log)

**Comment by harryfei** [comment]
I get the same error when I built on `arm-linux-androideabi`.
