### ISSUE TITLE
SystemSource::new() leaks memory

### ISSUE THREAD

**Issue by memoryleak47** [pcwalton/font-kit#86]
The following program persistenly increases its memory usage.

```rust
use font_kit::source::SystemSource;

fn main() {
    loop { SystemSource::new(); }
}
```

**Comment by jdm** [comment]
SystemSource is a different underlying implementation based on the platform in use. Which platform are you using?

**Comment by memoryleak47** [comment]
I'm using Arch Linux

**Comment by jdm** [comment]
Looks like we're missing a Drop implementation for [fc::Config](https://github.com/pcwalton/font-kit/blob/721df5dd217839e0194e973da9ba573c2fb587dd/src/sources/fontconfig.rs#L291-L304) that calls [FcConfigDestroy](https://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcconfigdestroy.html).
