### ISSUE TITLE
Support/Enable LCD filtering for subpixel antialiased text

### ISSUE THREAD

**Issue by mrandri19** [pcwalton/font-kit#95]
Currently, when rendering a glyph on Linux using the FreeType renderer and          `RasterizationOptions::SubpixelAa` there is no LCD filtering.

It looks like this, with very noticeable color fringing:
![image](https://user-images.githubusercontent.com/8144521/63598274-873f2a80-c5bf-11e9-8075-3258844a8254.png)

To enable filtering with FreeType `FT_Library_SetLcdFilter` should be set, but I don't know how that would work on other platforms.

The easiest solution would be to keep it transparent to the user and always use  `FT_LCD_FILTER_DEFAULT` with FreeType. I could try to make a pull request for that if this solution works for you.

**Comment by pcwalton** [comment]
Let's use `FT_LCD_FILTER_DEFAULT`.

**Comment by pcwalton** [comment]
Also yikes, that's a big oversight! Thanks for catching it.

**Comment by heftig** [comment]
FTR, if the current FreeType is compiled without support for LCD filters (and thus `FT_Library_SetLcdFilter` always fails), it will produce output almost identical to `FT_LCD_FILTER_LIGHT`.

Maybe that's why this was overlooked.
